libostree: Link with libgpg-error for gpg_strerror_r API
With f461c02bb55bf2853a3b81ed5c8618040ab54e98 use of gpg_strerror_r
was added this symbol comes from libgpg-error however, therefore its
needed to add -lgpg-error to cmdline to resolve this symbol especially
with gold and lld linker. Fixes

aarch64-yoe-linux-ld.lld: error: undefined reference due to --no-allow-shlib-undefined: gpg_strerror_r
>>> referenced by ./.libs/libostree-1.so

Upstream-Status: Submitted [https://github.com/ostreedev/ostree/pull/2880]
Signed-off-by: Khem Raj <raj.khem@gmail.com>

%% original patch: 0001-libostree-Link-with-libgpg-error-for-gpg_strerror_r-.patch